-- ════════════════════════════════════════════════════════════════════════
--  Post Tracker — initial schema
--
--  Run this in the Supabase SQL editor (or via `supabase db push`).
--
--  Tables:
--    tracked_accounts  — the influencer accounts we scrape
--    posts             — one row per unique post (dedup key = post_url).
--                        Raw stats are scraped; metric columns are computed
--                        by Postgres (generated columns) so they're always
--                        consistent and "look like the spreadsheet".
--    post_snapshots    — append-only history: one row per post per scrape,
--                        so you can track how a post's stats grow over time.
-- ════════════════════════════════════════════════════════════════════════

-- gen_random_uuid() is provided by pgcrypto (preinstalled on Supabase).
create extension if not exists pgcrypto;

-- ── Accounts we track ───────────────────────────────────────────────────
create table if not exists public.tracked_accounts (
  id            uuid primary key default gen_random_uuid(),
  platform      text not null check (platform in ('instagram', 'tiktok')),
  username      text not null,
  display_name  text,                    -- real name, shown in the dashboard
  active        boolean not null default true,
  follower_count bigint,                 -- cached follower count
  follower_checked_at timestamptz,       -- when followers were last fetched (cost throttle)
  last_scraped_at timestamptz,           -- when posts were last scraped
  created_at    timestamptz not null default now(),
  unique (platform, username)
);

-- ── Posts (latest stats; one row per unique post) ───────────────────────
create table if not exists public.posts (
  id              uuid primary key default gen_random_uuid(),
  post_url        text not null unique,            -- dedup key
  platform        text not null check (platform in ('instagram', 'tiktok')),
  influencer_name text not null,
  caption         text,
  post_type       text,                            -- Reel / Post / Image / Carousel / Video
  hashtags        text[] not null default '{}',

  -- raw scraped stats
  video_plays     bigint,
  follower_count  bigint,
  comments_count  bigint,
  share_count     bigint,
  likes           bigint,

  -- dates
  post_date       date,
  data_date       date,                            -- when these stats were captured

  -- ── computed metrics (generated by Postgres) ──────────────────────────
  -- Total Interactions = likes + comments + shares
  total_interactions bigint generated always as (
    coalesce(likes,0) + coalesce(comments_count,0) + coalesce(share_count,0)
  ) stored,

  -- Engagement Rate (%) = total interactions / followers
  engagement_rate_pct numeric(12,2) generated always as (
    round((coalesce(likes,0) + coalesce(comments_count,0) + coalesce(share_count,0))::numeric
          / nullif(follower_count,0) * 100, 2)
  ) stored,

  -- Comment-to-Like Ratio (%) = comments / likes
  comment_to_like_pct numeric(12,2) generated always as (
    round(coalesce(comments_count,0)::numeric / nullif(likes,0) * 100, 2)
  ) stored,

  -- Share-to-View Ratio (%) = shares / video plays
  share_to_view_pct numeric(12,2) generated always as (
    round(coalesce(share_count,0)::numeric / nullif(video_plays,0) * 100, 2)
  ) stored,

  -- Engagement-to-Views (%) = total interactions / video plays
  engagement_to_views_pct numeric(12,2) generated always as (
    round((coalesce(likes,0) + coalesce(comments_count,0) + coalesce(share_count,0))::numeric
          / nullif(video_plays,0) * 100, 2)
  ) stored,

  -- Content Resonance (%) = share of interactions that are likes
  content_resonance_pct numeric(12,2) generated always as (
    round(coalesce(likes,0)::numeric
          / nullif(coalesce(likes,0) + coalesce(comments_count,0) + coalesce(share_count,0), 0) * 100, 2)
  ) stored,

  -- Influencer Efficiency (%) = views generated per follower (reach efficiency)
  influencer_efficiency_pct numeric(12,2) generated always as (
    round(coalesce(video_plays,0)::numeric / nullif(follower_count,0) * 100, 2)
  ) stored,

  -- Virality Index (%) = shares as a share of total interactions
  virality_index_pct numeric(12,2) generated always as (
    round(coalesce(share_count,0)::numeric
          / nullif(coalesce(likes,0) + coalesce(comments_count,0) + coalesce(share_count,0), 0) * 100, 2)
  ) stored,

  raw         jsonb,                                -- full Apify item, for reference
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists posts_influencer_idx on public.posts (influencer_name);
create index if not exists posts_platform_idx   on public.posts (platform);
create index if not exists posts_post_date_idx   on public.posts (post_date desc);

-- ── Snapshot history (append-only) ──────────────────────────────────────
create table if not exists public.post_snapshots (
  id              uuid primary key default gen_random_uuid(),
  post_url        text not null,
  captured_at     timestamptz not null default now(),
  video_plays     bigint,
  follower_count  bigint,
  comments_count  bigint,
  share_count     bigint,
  likes           bigint,
  total_interactions bigint generated always as (
    coalesce(likes,0) + coalesce(comments_count,0) + coalesce(share_count,0)
  ) stored,
  engagement_rate_pct numeric(12,2) generated always as (
    round((coalesce(likes,0) + coalesce(comments_count,0) + coalesce(share_count,0))::numeric
          / nullif(follower_count,0) * 100, 2)
  ) stored
);

create index if not exists snapshots_post_url_idx on public.post_snapshots (post_url, captured_at desc);

-- ── keep posts.updated_at fresh ─────────────────────────────────────────
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists posts_set_updated_at on public.posts;
create trigger posts_set_updated_at
  before update on public.posts
  for each row execute function public.set_updated_at();

-- ── Row Level Security ──────────────────────────────────────────────────
-- All app access is server-side with the service-role key, which bypasses
-- RLS. We enable RLS with no public policies so the anon key cannot read
-- the data directly.
alter table public.tracked_accounts enable row level security;
alter table public.posts           enable row level security;
alter table public.post_snapshots  enable row level security;

-- ── Seed the accounts to track ──────────────────────────────────────────
insert into public.tracked_accounts (platform, username, display_name) values
  ('instagram', 'lindseyranzau',       'Lindsey Ranzau'),
  ('instagram', 'jbird929',            'Jenny Anderson Brown'),
  ('instagram', 'ali_denae',           'Alicia Metzen'),
  ('instagram', 'josijamesco',         'Alicia Metzen (josijamesco)'),
  ('instagram', 'meganstuartt',        'Megan Stuart'),
  ('instagram', 'sadie.carlisle',      'Sadie Carlisle'),
  ('instagram', 'lifeintheflaschlane', 'Amy Flasch')
on conflict (platform, username) do nothing;
